### ISSUE TITLE
Get separtely cedges and vedges

### ISSUE THREAD

**Issue by danielui** [CiscoDevNet/vManage-client#112]
### Description

Currently in Device dataclass, there is one personality for cedges and vedges - edges. In certain cases, there is need to differentiate those two types of devices.

**Comment by tehAgitto** [comment]
Can we just add `vEdge` and `cEdge` into `Personality` Enum and replace `Edge` with AND `&` operator?

**Comment by danielui** [comment]
Yes, we can. Problem is, how to get those personalities from vManage API.

**Comment by kagorskii** [comment]
Is it possible to get that information from device model? Thats probably overkill, because we had to create a new map for this :/

**Comment by tehAgitto** [comment]
We cannot provide map in our client, this should be covered from the app side. vmngclient should be compatible with vManage API, so if vManage doesn't distinguishes between cEdge and vEdge, it could be not compatible with other APIs if such map would be provided.
