### ISSUE TITLE
PR unable to merge

### ISSUE THREAD

**Issue by tomaszwarda** [CiscoDevNet/vManage-client#174]
### Summary

PR is unable to merge if only `.md` files are edited, because unittest and analyze_workflow are ignoring those files. But merging changes require all checks to pass which is not happening, because 2 of 3 are not even started.

### Proposed fix:

Delate from workflows those lines
```yml
    paths-ignore:
      - '**.md'
```

### Logs and external information

![image](https://user-images.githubusercontent.com/85410520/225413420-fb17bb3d-81b7-409a-becb-92b51562b02a.png)

### Reproduction script

Make a PR with changes only to `.md` file.

### On what platform(s) does it occur?

Not Applicable

### Issue Severity

None

**Comment by sbasan** [comment]
There is other solution which will not produce unnecessary workload:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
