### ISSUE TITLE
Nested dataclasses in serialization and deserialization

### ISSUE THREAD

**Issue by tomaszwarda** [CiscoDevNet/vManage-client#210]
### Description

We should cover nested dataclasses in our serialization and deserlilization.
>We should cover that inside `dataseq` method or re-define our deserialization
_Originally posted by @tehAgitto in https://github.com/CiscoDevNet/vManage-client/pull/209#discussion_r1160537912_

**Comment by tehAgitto** [comment]
Serialization and deserialization is already being covered by `pydantic-v2`. `attrs` won't be used anymore #422
