### ISSUE TITLE
Why check for user's existence?

### ISSUE THREAD

**Issue by vj68** [CiscoDevNet/vManage-client#230]
### Summary

1) Why are we checking for the user's existence before calling the APIs to create/delete a user?

This can be a problem if we want to measure the time taken to create/delete a user, because this would also include the time to get the users - `self.exists(username)`

Can we not rely on the API's response itself to know if the operation was successful or not?
Or is there a way to know the exact time for create/delete user APIs?

2) These APIs only return True/False. How can we get the actual JSON response?
```python
# vmngclient/api/administration.py
    def create_user(self, user: User) -> bool:
        if self.exists(user.username):
            raise UserAlreadyExistsError(f"{user.username} already exists.")
        url_path = "/dataservice/admin/user"
        data = asdict(user)  # type: ignore

        response = self.session.post(url=url_path, json=data)
        logger.info(response)
        return True if response.status_code == 200 else False

    def delete_user(self, username: str) -> bool:
        if not self.exists(username):
            raise UserDoesNotExists(f"{username} does not exists.")
        url_path = f"/dataservice/admin/user/{username}"
        logger.debug(f"Deleting user {username}.")
        response = self.session.delete(url_path)
        return True if response.status_code == 200 else False
```

### Logs and external information

N/A

### Reproduction script

```python
u = User(username="u5", password="u5", group=["netadmin"], description="u5")
answer = UsersAPI(session).create_user(u)

answer = UsersAPI(session).delete_user("u5")
```

### On what platform(s) does it occur?

Linux

### Issue Severity

Low: It annoys me

**Comment by tehAgitto** [comment]
Thanks for pointing that out. `UsersAPI` should be marked as deprecated. Since introducing layer separation in #211 we should rewrite the whole `UsersAPI` to support ONLY single endpoints (layer 2) and build the logic upon on that (layer 3).

To sum up:
1. We should not check the User's existence
2. We should return already implemented `vManageResponse` object.
