### ISSUE TITLE
Not logging out on session destroy

### ISSUE THREAD

**Issue by vj68** [CiscoDevNet/vManage-client#233]
### Summary

User session is not destroyed when the session variable is destroyed. User sessions can still be seen after the script execution is finished.
I also can't see any call to `/logout` API in `vmngclient.log`

### Logs and external information

N/A

### Reproduction script

```python
    with create_vManageSession(url=url, username=username, password=password) as session:
        ...
```

Also tried to explicitly close the session, but didn't help
```python
    with create_vManageSession(url=url, username=username, password=password) as session:
        ...
        session.close()
```

### On what platform(s) does it occur?

Linux

### Issue Severity

High: Blocking everything

**Comment by sbasan** [comment]
Yes, definately we want this to happen (It is planned actually in #82)
Please note that using session.close() you just clost socket. In our case we need to do explicit logout request on vManage.

**Comment by tehAgitto** [comment]
Pinned #82 into 1.0.0 release
