### ISSUE TITLE
relogin_request() doesn't fit our requirements

### ISSUE THREAD

**Issue by tehAgitto** [CiscoDevNet/vManage-client#25]
### Description

vManage token expires automatically, so it needs to be fetched periodically. 

`relogin_request()` should be used only if relogin is really required. Currently it is used for every requests which can impact on the performance of the client. The new way of the authentication to vManage should be separated from the `session` code, so it can be extended for completely new ways of authentication.

**Comment by tehAgitto** [comment]
#34 Removes relogin_request(). 
Relogin is still not implemented. It should be investigated when relogin is necessary.

**Comment by tehAgitto** [comment]
1. Is there a variable responsible for the SESSION timeout
2. If so, we retrieve this variable and put this time into the `vManageAuth` object as `self.expiration_time`
3. We slightly need to change the code in `__call__` so that it takes into account the token refresh time

**Comment by tomaszwarda** [comment]
#150 renews session after it expired
