### ISSUE TITLE
[L2] "The golden" request

### ISSUE THREAD

**Issue by tehAgitto** [CiscoDevNet/vManage-client#282]
### Description

By the enormous scale on which vManage operates and for how many years - we need to create  some sort of the golden request. The goal is to reduce boilerplate code and to automate API calls. 

To create a request, user needs to provide:
- Datamodel
- Endpoint
- Version(s) of vManage
- Additional parameters, headers, etc. (Optional as decorator)
- Views to operate

```python
    @request(url="/device", payload=devices) # This could be Optional
    @Versions(">=20.4")
    @View({ProviderView}) # By default, works on every View
    def foo(self, devices: List[Device]) -> Device:
        """ Available only as Provider and 20.4+ version of vManage.  """ # Add information about versions, available views.
        response = self.request("/device", payload=devices) # Could be replaced by decorator
        return response.dataobj(Device, None) # Could be replaced by return obj
```

Moreover, need to investigate if overload format is possible. This could help to version vManage-client very easliy.

```python
    @Versions("<=20.3")
    @View({ProviderView, ProviderAsTenantView})
    def foo(self, devices: List[Device]) -> Device:
        """ Available only as Provider and 20.3 or lower version of vManage.  """
        response = self.request("/device", payload=devices)
        return response.dataobj(Device, None)
```

Additional decorators could be provided
```python
@PublicAPI # Instead of copying code into `api` containter or use `primitive` container, we can public primitives for the user.
```

**Comment by sbasan** [comment]
For the record, idea of declarative api layer is very similar to:
https://uplink.readthedocs.io/en/latest/index.html
which is inspired by:
https://square.github.io/retrofit/
