### ISSUE TITLE
allow custom platform version when parsing GET /client/server

### ISSUE THREAD

**Issue by sbasan** [CiscoDevNet/vManage-client#309]
### Summary

We need to update model to allow versions not matching packaging scheme. eg.: '20.12.0-144-li'

### Logs and external information

'20.12.0-144-li'

### Reproduction script

try create a session for vManage with platform version '20.12.0-144-li'

### On what platform(s) does it occur?

Not Applicable

### Issue Severity

High: Blocking everything

**Comment by JimOverholt** [comment]
In cases like this would be better to leave that attribute incomplete with a warning and not block session creation.

**Comment by igosoft** [comment]
I agree. No need to block and build to complex logic. I suggest to follow Software Versioning Scheme firstly and warn user if retrieved value doesn't match pattern
