### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by tehAgitto** [CiscoDevNet/vManage-client#4]
### Description

- [x] Workflows #3 
- [x] Issue templates #3 
- [x] #81
- [x] README #54 
- [x] Poetry #3 
- [ ] Tests
- [x] Codebase #3 
- [x] Publish on PyPI https://pypi.org/project/vmngclient/

**Comment by tehAgitto** [comment]
add: publish on PyPI

**Comment by tehAgitto** [comment]
https://pypi.org/project/vmngclient/

**Comment by tomaszwarda** [comment]
Tests:
- [ ] `admin_tech.py`
- [ ] `administration.py`
- [ ] `alarms_api.py`
- [ ] `basic_api.py`
- [ ] `device_action_api.py`
- [ ] `logs_api.py`
- [x] `omp_api.py`  #42 
- [ ] `packet_capture_api.py`
- [ ] `speedtest_api.py`
- [x] `templates.py` #11

**Comment by tehAgitto** [comment]
CONTRIBUTING file was not present in first repo, therefore it shouldn't be tracked here. A new issue has been opened #80
