### ISSUE TITLE
Failed login - clear Exception

### ISSUE THREAD

**Issue by tehAgitto** [CiscoDevNet/vManage-client#45]
### Description

![image](https://user-images.githubusercontent.com/33100242/205050522-f44be96a-5e9e-478d-ab4c-81ca26f6b0ef.png)
Include the same options into session login Exception

**Comment by tomaszwarda** [comment]
For now when login fails it shows full login and password.
It should not show what password the user is using.
Line where the password is shown in [`vmngclient/vmanage_auth.py`](https://github.com/CiscoDevNet/vManage-client/blob/main/vmngclient/vmanage_auth.py#L31)

Made PR for it #77

**Comment by tomaszwarda** [comment]
PR #77 merged, password hidden.

**Comment by danielui** [comment]
Full message available only in html file.
