### ISSUE TITLE
Response hooks.

### ISSUE THREAD

**Issue by tehAgitto** [CiscoDevNet/vManage-client#57]
### Description

Check if it is possible to move parse response data into requests hooks.

**Comment by sbasan** [comment]
Not sure if parsing can be done in hook as it requires knowledge of dataclass prior parsing. Other solution is proposed.
Added parser methods to `vManageResponse' which inherits form `requests.Response`.
Introduced `vManageResponseAdapter` which wraps http methods to return extended response
