### ISSUE TITLE
Create contex manager for vManageSession object

### ISSUE THREAD

**Issue by tehAgitto** [CiscoDevNet/vManage-client#82]
### Description

- [ ] logout() #304 
- [ ] context_manager #304 

Login is already implemented in as an `auth` attribute.

**Comment by sbasan** [comment]
Maybe it is posible to create custom adapter which will logout on `close()` ?
https://requests.readthedocs.io/en/latest/api/#requests.adapters.BaseAdapter
Just an idea.

**Comment by sbasan** [comment]
`requests.Session` which is base class for `vManageSession` already has context manager which executes `close()` on `__exit__().
We need to implement `close()` method which will perform logout before calling `super()` which closes connections for adapters. To perform logout we need to send `PUT /logout` (or `GET /logout` prior vManage 20.12)

**Comment by tehAgitto** [comment]
closed by #304
