### ISSUE TITLE
Create mapping; vManageVersion -> [DeviceType -> Set of available feature templates]

### ISSUE THREAD

**Issue by tehAgitto** [CiscoDevNet/vManage-client#94]
- [x] Static checking (deprecated)

**Comment by tehAgitto** [comment]
The maintenance cost is too big to create static checking for such things. This will be replaced by dynamic validator which scraps every piece of information from vManage. 

Moreover it would be hard to create such mapping for session which hasn't got mandatory vManageVersion field.

**Comment by kagorskii** [comment]
#163 covers the issue.
